### ISSUE TITLE
Turn off Interactive login

### ISSUE THREAD

**Issue by Zoharat** [navikt/mock-oauth2-server#126]
I am trying to use the docker image in my test environment.

The application makes a request as 
http://oauthServer:8080/default/authorize?prompt=login&state=00000001fm5ccpbb470sgc1fe07mh66t&response_type=code&client_id=test&redirect_uri=https%3A%2F%2Fapp.test.com%3A8443%2Ftest%2Fwebservices%2Frest%2Foauth%2Freturn&scope=openid%20scope1%20scope2

my json config I have interactive set as false. 

But the return of invoking the above url I still get back an HTML page.

How can I just invoke the above url and get redirected back to return endpoint where I then make requests for tokens?
[config.txt](https://github.com/navikt/mock-oauth2-server/files/7514659/config.txt)

**Comment by tommytroen** [comment]
@Zoharat I'm afk at the moment, but on first glance you might get the login page as a result of sending 'login=prompt' in your auth url. Try removing that query param.

**Comment by Zoharat** [comment]
I though as well, so removed that but it did not help still got the login page.

**Comment by tommytroen** [comment]
Alright. I'll have a look when I'm on a laptop.

**Comment by Zoharat** [comment]
Hello,
Have you had a chance to reproduce it? Any updates?

**Comment by tommytroen** [comment]
@Zoharat I seems to work fine when removing the `login=prompt` query param on the latest version (`0.4.0`) when I tested. Both with the json config as an env var and as a mounted file. 

I tested with the following in docker-compose:
```yaml
services:
  server:
    image: ghcr.io/navikt/mock-oauth2-server:0.4.0
    ports:
      - "80:8080"
    environment:
      JSON_CONFIG: |
        {
          "interactiveLogin": false,
          "httpServer": "MockWebServerWrapper",
          "tokenCallbacks": [
            {
              "issuerId": "issuer1",
              "tokenExpiry": 120,
              "requestMappings": [
                {
                  "requestParam": "scope",
                  "match": "scope1",
                  "claims": {
                    "sub": "accessToken",
                    "aud": [
                      "accessToken"
                    ]
                  }
                },{
                  "requestParam": "scope",
                  "match": "scope2",
                  "claims": {
                    "sub": "refreshToken",
                    "aud": [
                      "refreshToken"
                    ]
                  }
                }
              ]
            }
          ]
        }
```

and with the same json config mounted as a file.

Maybe your config isn't set properly and therefore giving you the default behaviour. How do you specify your json config? And what version are you testing?
