### ISSUE TITLE
Wrong issuer value?

### ISSUE THREAD

**Issue by m1212e** [navikt/mock-oauth2-server#767]
Hi, I get this error when I try to run the container as a dev mock oidc instance:

```
  code: 'OAUTH_JSON_ATTRIBUTE_COMPARISON_FAILED',
  [cause]: {
    expected: 'http://localhost:8080/',
    body: {
      issuer: 'http://localhost:8080/.well-known/openid-configuration',
      authorization_endpoint: 'http://localhost:8080/.well-known/openid-configuration/authorize',
      end_session_endpoint: 'http://localhost:8080/.well-known/openid-configuration/endsession',
      revocation_endpoint: 'http://localhost:8080/.well-known/openid-configuration/revoke',
      token_endpoint: 'http://localhost:8080/.well-known/openid-configuration/token',
      userinfo_endpoint: 'http://localhost:8080/.well-known/openid-configuration/userinfo',
      jwks_uri: 'http://localhost:8080/.well-known/openid-configuration/jwks',
      introspection_endpoint: 'http://localhost:8080/.well-known/openid-configuration/introspect',
      response_types_supported: [Array],
      response_modes_supported: [Array],
      subject_types_supported: [Array],
      id_token_signing_alg_values_supported: [Array],
      code_challenge_methods_supported: [Array]
    },
    attribute: 'issuer'
  }
}
```

I use the `openid-client` npm package in Node.js to run OIDC requests etc. against the container.
```ts
	if (configPrivate.NODE_ENV === 'development') {
		execute.push(allowInsecureRequests);
	}
	const config = await discovery(
		new URL(configPublic.PUBLIC_OIDC_AUTHORITY),
		configPublic.PUBLIC_OIDC_CLIENT_ID,
		{
			client_secret: configPrivate.OIDC_CLIENT_SECRET,
			token_endpoint_auth_method: configPrivate.OIDC_CLIENT_SECRET ? undefined : 'none'
		},
		undefined,
		{
			execute
		}
	);
```
This is the container compose config:

```yml
  mockoidc:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.10
    ports:
      - 8080:8080
    environment:
      JSON_CONFIG: >
        {
          "interactiveLogin": true,
          "httpServer": "NettyWrapper",
          "tokenCallbacks": [
              {
                "issuerId": "issuer1",
                "tokenExpiry": 120,
                "requestMappings": [
                  {
                    "requestParam": "code",
                    "match": "code1",
                    "claims": {
                      "sub": "subByCode",
                      "aud": [
                          "audByCode"
                      ]
                    }
                  }
                ]
              }
          ]
        }
```

these are the configured env config vars:

```env
PUBLIC_OIDC_AUTHORITY=http://localhost:8080/
PUBLIC_OIDC_CLIENT_ID=issuer1
```

Do you happen to know whats causing this? I think I misconfigured the mock container but I cannot seem to find what I need to change! Thank you very much!
